# Nama: Anindyar Bintang Rahma Esa
# NIM : 230103197
# Proyek: student_performance_tracker

from pathlib import Path

def build_markdown_report(records):
    """
    Membuat tabel laporan dalam format Markdown dari data rekap.

    Args:
        records (list): List of dictionaries hasil dari RekapKelas.rekap().

    Returns:
        str: String multi-baris berisi tabel Markdown.
    """
    lines = [
        "# Rekap Nilai Mahasiswa",
        "",
        "| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |",
        "|---|---|---:|---:|:---:|"
    ]
    
    for r in records:
        lines.append(
            "| {nim} | {nama} | {hadir:.2f} | {akhir:.2f} | {pred} |".format(
                nim=r["nim"],
                nama=r["nama"],
                hadir=r["hadir_persen"],
                akhir=r["nilai_akhir"],
                pred=r["predikat"]
            )
        )
        
    lines.append("")
    lines.append("Generated by student_performance_tracker.")
    return "\n".join(lines)


def save_text(path_str, content):
    """
    Menyimpan konten string ke dalam file teks.
    Fungsi ini akan otomatis membuat folder 'out' jika belum ada.

    Args:
        path_str (str): Path tujuan file, misal "out/report.md".
        content (str): Konten teks yang akan disimpan.
    """
    try:
        p = Path(path_str)
        # Membuat direktori induk (misal 'out/') jika belum ada
        p.parent.mkdir(parents=True, exist_ok=True)
        
        # Menulis file
        p.write_text(content, encoding="utf-8")
        print(f"Laporan berhasil disimpan di: {p.resolve()}")
        
    except IOError as e:
        print(f"Gagal menyimpan file: {e}")
    except Exception as e:
        print(f"Terjadi error tak terduga saat menyimpan file: {e}")